version: 2.1

executors:
  windows-executor:
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.medium
    shell: powershell.exe -ExecutionPolicy Bypass

jobs:
  build_windows:
    executor: windows-executor
    steps:
      - run:
          name: Print Java Version
          command: 'java -version'

      - checkout

      - run:
          name: Gradle Version
          command: './gradlew -v'

workflows:
  version: 2
  build:
    jobs:
      - build_windows:
          filters:
            branches:
              only:
                - master
                - /^release$/
                - /.*release.*/