version: 2.1

executors:
  windows-executor:
    docker:
      - image: azul/zulu-openjdk:17.0.9
  macos-executor:
    macos:
      xcode: "12.5.1"

jobs:
  build_windows:
    executor: windows-executor
    working_directory: ~/repo

    steps:
      - checkout

#      - run:
#          name: Install dependencies
#          command: |
#            # Install any necessary Windows dependencies
#            choco install -y jdk8
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

#      - run:
#          name: Build JavaFX application for Windows
#          command: |
#            ./gradlew clean assemble

#      - run:
#          name: Create installer for Windows
#          command: |
#            echo "Hi from window...."
#            ./gradlew dependencies
#            ./gradlew jlink
#            ./gradlew jpackage
#            ./gradlew jlinkzip
#            ./gradlew convertMarkdownToPdf
#            ./gradlew buildDocs
#            jpackage --input build/libs --main-jar myApp.jar --name MyApp --main-class com.example.Main --type exe --win-dir-chooser --win-shortcut

  build_macos:
    executor: macos-executor
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            # Install any necessary macOS dependencies
            # Example: brew install some-package

      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: Build JavaFX application for macOS
          command: |
            ./gradlew clean assemble

      - run:
          name: Create installer for mac
          command: |
            echo "Hi from Mac...."
            ./gradlew dependencies
            ./gradlew jpackage
            ./gradlew convertMarkdownToPdf
            ./gradlew buildDocs
#            jpackage --input build/libs --main-jar myApp.jar --name MyApp --main-class com.example.Main --type pkg --mac-bundle-name MyApp

workflows:
  version: 2
  build:
    jobs:
      - build_windows
      - build_macos
