version: 2.1

orbs:
  win: circleci/windows@5.0

executors:
  linux-executor:
    docker:
      - image: arnab2203/test_linux_image:cache2.1  # Pre-built Linux Docker image
#      - image: arnab2203/test_windows_image:1.1  # Pre-built Linux Docker image

#  windows-executor:
#    working_directory: ~/project
#    resource_class: large
#    docker:
#      - image: mopriadevteam/win_exec:2.1
#    shell: powershell.exe -ExecutionPolicy Bypass

jobs:
  tcl_task:
    executor: linux-executor
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false
      TERM: dumb

    steps:

      - run:
          name: git version
          command: 'git --version'

      - run:
          name: ssh version
          command: 'ssh -V'

      - checkout

      - run:
          name: Pandoc version
          command: 'pandoc --version'

      - run:
          name: Texlive version
          command: 'tex --version'

      - run: 'chmod +x ./gradlew'

      - run:
          name: Gradle Version
          command: './gradlew -v'


  build_windows:
    executor:
      name: win/default
    steps:

      # Restore the cache for choco packages
      - restore_cache:
          keys:
            - choco-cache-v1-{{ checksum "choco-packages.config" }}
            - choco-cache-v1-

      - run: choco install --confirm zulu17

      - run:
          name: Print Java Version
          command: 'java -version'

      - checkout

      # Grant executable permission to gradlew
      - run:
          name: Set gradlew executable permission
          command: chmod +x ./gradlew

      - run:
          name: Gradle Version
          command: |
            chmod +x ./gradlew

      - run:
          name: Install Pandoc
          command: |
            choco install pandoc -y
            choco install rsvg-convert python miktex -y

      - run:
          name: Pandoc version
          command: 'pandoc --version'

      # Check Chocolatey version
      - run:
          name: Check choco version
          command: |
            choco --version


      - run:
          name: Install WiX Toolset
          command: |
            choco install wixtoolset --version=3.14.1 -y
            
      # Check WiX Toolset version
      - run:
          name: Check WiX Toolset version
          command: |
            candle.exe -v || echo "WiX Toolset is not installed"
            light.exe -v || echo "WiX Toolset is not installed"
            

      # Save the choco cache
      - save_cache:
          paths:
            - C:\ProgramData\chocolatey\lib
          key: choco-cache-v1-{{ checksum "choco-packages.config" }}



#  mct_build:
#    executor: linux-executor
#    steps:
#      - attach_workspace:
#          at: build
#
#      - store_artifacts:
#          path: build/jpackage
#          destination: .
#
#      - store_artifacts:
#          path: build/tcl
#          destination: tcl/.

workflows:
  version: 2
  build:
    jobs:
      - tcl_task
      - build_windows:
          requires:
            - tcl_task

#          filters:
#            branches:
#              only:
#                - master
#                - /^release$/
#                - /.*release.*/

#      - mct_build:
#          filters:
#            branches:
#              only:
#                - master
#                - /^release$/
#                - /.*release.*/
#          requires:
#            - build_windows