# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  win: circleci/windows@5.0.0
  jobs:
    build:
      executor: win/server-2022
      steps:
        - run: Write-Host 'Hello, Windows'

workflows:
  win-workflow:
    jobs:
      - build