# Use the Windows Server Core base image
FROM mcr.microsoft.com/windows/servercore:ltsc2022 AS builder

# Set the working directory
#WORKDIR C:\app

# Install Chocolatey
RUN powershell -Command \
    Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# Install necessary packages
RUN choco install --yes zulu17 pandoc rsvg-convert python miktex wixtoolset

# Install .NET Framework
RUN powershell -Command Install-WindowsFeature Net-Framework-Core

# Set up the entry point
ENTRYPOINT ["powershell.exe"]