# Use the official Azul Zulu OpenJDK image
FROM azul/zulu-openjdk:17.0.10

# Set environment variables for Gradle
ENV GRADLE_VERSION=8.2
ENV GRADLE_HOME=/opt/gradle
ENV PATH=${GRADLE_HOME}/gradle-${GRADLE_VERSION}/bin:${PATH}

# Install necessary tools and clean up afterwards to reduce image size
RUN apt-get update && \
    apt-get install -y wget curl git openssh-client fakeroot pandoc graphviz \
    texlive-latex-recommended texlive-fonts-recommended python3-pip  \
    unzip \
    gettext-base && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set JVM and Gradle options
ENV JVM_OPTS="-Xmx2048m"
ENV GRADLE_OPTS="-Xmx2048m -Dorg.gradle.daemon=false"
ENV TERM="dumb"

# Download and install Gradle
RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip && \
    unzip gradle-${GRADLE_VERSION}-all.zip -d /opt/gradle && \
    rm gradle-${GRADLE_VERSION}-all.zip

# Verify Gradle installation
RUN gradle --version

# Set the working directory for the application
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Set the entry point (adjust as necessary)
ENTRYPOINT ["bash"]
