# Use the official Azul Zulu OpenJDK image
FROM azul/zulu-openjdk:17.0.10

# Set the working directory
WORKDIR /app

# Install necessary tools
RUN apt-get update && apt-get install -y && apt-get install curl -y \
    git \
    openssh-client \
    fakeroot \
    pandoc \
    graphviz \
    texlive-latex-recommended \
    texlive-fonts-recommended \
    python3-pip \
    gettext-base \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV JVM_OPTS=-Xmx2048m
ENV GRADLE_OPTS=-Xmx2048m -Dorg.gradle.daemon=false
ENV TERM=dumb

# Install Gradle (you can specify the version you need)
RUN curl -s https://get.sdkman.io | bash && \
    bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install gradle"

# Set the entry point (adjust as necessary)
ENTRYPOINT ["bash"]