# Use the official Azul Zulu OpenJDK image
FROM azul/zulu-openjdk:17.0.10

# Set the working directory
WORKDIR /app

# Install necessary tools
RUN apt-get update && apt-get install -y && apt-get install wget -y \
    git \
    openssh-client \
    fakeroot \
    pandoc \
    graphviz \
    texlive-latex-recommended \
    texlive-fonts-recommended \
    python3-pip \
    gettext-base \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV JVM_OPTS=-Xmx2048m
ENV GRADLE_OPTS=-Xmx2048m -Dorg.gradle.daemon=false
ENV TERM=dumb

# Download and install Gradle
#ENV GRADLE_VERSION=8.2
#RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -O /tmp/gradle.zip \ && unzip /tmp/gradle.zip -d /opt/ \ && ln -s /opt/gradle-${GRADLE_VERSION}/bin/gradle /usr/bin/gradle \ && rm /tmp/gradle.zip
## Verify the installation
#RUN gradle --version

# Set the entry point (adjust as necessary)
ENTRYPOINT ["bash"]